version: '3.8'

services:
  nginx:
    image: ${DOCKER_USERNAME}/nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    image: ${DOCKER_USERNAME}/spring-app:${IMAGE_TAG}
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    healthcheck: # 헬스체크 추가
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge