version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy  # app이 건강한 상태일 때만 시작
    restart: always
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: [ "CMD-SHELL", "apk add --no-cache curl && curl -f http://localhost/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    image: ${DOCKER_USERNAME}/spring-app:${IMAGE_TAG}
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    networks:
      - app-network
    healthcheck: # 헬스체크 추가
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s    # 애플리케이션 시작 대기 시간

networks:
  app-network:
    driver: bridge