version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: library_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - library-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: library_logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - library-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: library_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - library-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.10
    container_name: library_filebeat
    user: root
    environment:
      - setup.kibana.host=kibana:5601
      - output.logstash.hosts=["logstash:5044"]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log/app:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -strict.perms=false  # 권한 체크를 비활성화
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - library-network

  redis:
    image: redis:6.2
    container_name: library_redis
    command: redis-server --requirepass
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - library-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: library_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - library-network

volumes:
  elasticsearch-data:
  redis-data:
  rabbitmq-data:

networks:
  library-network:
    driver: bridge

