version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: library_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - library-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: library_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - library-network

  redis:
    image: redis:6.2
    container_name: library_redis
    command: redis-server --requirepass
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - library-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: library_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - library-network

volumes:
  elasticsearch-data:
  redis-data:
  rabbitmq-data:

networks:
  library-network:
    driver: bridge

