branch-defaults:
  main:
    environment: Librarymanagement-env
    group_suffix: null
global:
  application_name: library_management
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2  # Amazon Linux 2 사용
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application