name: Deploy to Production

on:
  push:
    branches: [ feature/ci_cd ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}
  EB_APP_NAME: library_management
  EB_ENV_NAME: Librarymanagement-env
  AWS_REGION: ap-northeast-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Docker 관련 단계 추가
      - name: Set up Docker Buildx    # Docker 빌드 도구 설정
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub     # Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    # Docker Hub Access Token

      - name: Build and push Spring Boot image    # Spring Boot 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ github.sha }}

      # EC2 직접 배포 대신 Elastic Beanstalk 배포로 변경
      - name: Clean up old versions
        run: |
          versions=$(aws elasticbeanstalk describe-application-versions \
            --application-name ${{ env.EB_APP_NAME }} \
            --query 'ApplicationVersions[*].VersionLabel' \
            --output text)

          for version in $versions; do
            aws elasticbeanstalk delete-application-version \
              --application-name ${{ env.EB_APP_NAME }} \
              --version-label "$version" \
              --delete-source-bundle \
              --force-delete || true
          done

      - name: Generate deployment package
        run: |
          # Docker config 생성
          mkdir -p ~/.docker
          echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'$(echo -n "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" | base64)'"}}}' > ~/.docker/config.json
          
          # 환경변수 설정 파일 생성
          cat > .ebextensions/03-environment.config << EOF
          files:
            "/opt/elasticbeanstalk/hooks/appdeploy/pre/03_set_env.sh":
              mode: "000755"
              owner: root
              group: root
              content: |
                #!/bin/bash
                # 환경변수 파일 생성
                ENV_FILE="/opt/elasticbeanstalk/deployment/env"
          
                # 기존 파일 백업
                [ -f "$ENV_FILE" ] && cp "$ENV_FILE" "${ENV_FILE}.bak"
          
                # 새 환경변수 설정
                cat > "$ENV_FILE" << EOL
                export REDIS_PASSWORD='${{ secrets.REDIS_PASSWORD }}'
                export REDIS_SENTINEL_NODES='${{ secrets.REDIS_SENTINEL_NODES }}'
                export DB_HOST='${{ secrets.DB_HOST }}'
                export DB_USERNAME='${{ secrets.DB_USERNAME }}'
                export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
                export JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'
                export OWNER_TOKEN='${{ secrets.OWNER_TOKEN }}'
                export TOSS_SECRET_KEY='${{ secrets.TOSS_SECRET_KEY }}'
                export TOSS_CLIENT_KEY='${{ secrets.TOSS_CLIENT_KEY }}'
                export TOSS_SUCCESS_URL='${{ secrets.TOSS_SUCCESS_URL }}'
                export TOSS_FAIL_URL='${{ secrets.TOSS_FAIL_URL }}'
                export TOSS_BASE_URL='${{ secrets.TOSS_BASE_URL }}'
                export SPRING_PROFILES_ACTIVE=prod
                EOL
          
                # 권한 설정
                chmod 600 "$ENV_FILE"
          
                # 환경변수 로드
                source "$ENV_FILE"
          
          container_commands:
            01_verify_env:
              command: |
                echo "Verifying deployment environment..."
                if [ ! -f /opt/elasticbeanstalk/deployment/env ]; then
                  echo "Environment file not found!"
                  exit 1
                fi
                
                required_vars=(
                  "REDIS_PASSWORD"
                  "REDIS_SENTINEL_NODES"
                  "DB_HOST"
                  "DB_USERNAME"
                  "DB_PASSWORD"
                  "JWT_SECRET_KEY"
                  "OWNER_TOKEN"
                  "TOSS_SECRET_KEY"
                  "TOSS_CLIENT_KEY"
                  "TOSS_SUCCESS_URL"
                  "TOSS_FAIL_URL"
                  "TOSS_BASE_URL"
                )
                
                missing_vars=0
                for var in "\${required_vars[@]}"; do
                  if [ -z "\${!var}" ]; then
                    echo "Error: $var is not set"
                    missing_vars=$((missing_vars + 1))
                  fi
                done
                
                if [ $missing_vars -gt 0 ]; then
                  echo "Missing $missing_vars required environment variables"
                  exit 1
                fi
          EOF
          
          # Dockerrun.aws.json 환경 변수 치환
          sed -i "s|\${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g" Dockerrun.aws.json
          sed -i "s|\${IMAGE_TAG}|${{ github.sha }}|g" Dockerrun.aws.json
          
          # 배포 패키지 생성
          zip -r deploy.zip Dockerrun.aws.json .ebextensions/* .elasticbeanstalk/* ~/.docker/config.json

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APP_NAME }}
          environment_name: ${{ env.EB_ENV_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_deployment: true

      # 배포 후 헬스체크
      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          # 배포 완료 대기 시간 증가
          sleep 60
          
          # Elastic Beanstalk 환경 URL 가져오기
          EB_ENV_URL=$(aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENV_NAME }} \
            --query 'Environments[0].CNAME' \
            --output text)
          
          echo "Checking health at: http://${EB_ENV_URL}/actuator/health"
          
          # 최대 5번 재시도
          for i in {1..5}
          do
            response=$(curl -s -o /dev/null -w "%{http_code}" "http://${EB_ENV_URL}/actuator/health" || echo "failed")
            if [ "$response" = "200" ]; then
              echo "Health check successful!"
              exit 0
            fi
            echo "Attempt $i: Health check failed with status: $response"
            sleep 30
          done
          
          echo "Health check failed after 5 attempts"
          
          # 로그 확인
          aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENV_NAME }} \
            --query 'Environments[0].Health' \
            --output text
          
          # 최근 이벤트 확인
          aws elasticbeanstalk describe-events \
            --environment-name ${{ env.EB_ENV_NAME }} \
            --max-items 10
          
          exit 1